from genome import *

def test_frequent_words_1():
	assert(("CATG" and "GCAT") in frequent_words("ACGTTGCATGTCGCATGATGCATGAGAGCT",4))

def test_frequent_words_2():
	assert("TGG" in frequent_words("""TGGTAGCGACGTTGGTCCCGCCGCTTGAGAATCTGGATGAACATAAGCTCCCACTTGGCTTATT
CAGAGAACTGGTCAACACTTGTCTCTCCCAGCCAGGTCTGACCACCGGGCAACTTTTAGAGCAC
TATCGTGGTACAAATAATGCTGCCAC""",3))

def test_frequent_words_3():
	assert("TTTT" in frequent_words("""CAGTGGCAGATGACATTTTGCTGGTCGACTGGTTACAACAACGCCTGGGGCTTTTGAGCAACGA
GACTTTTCAATGTTGCACCGTTTGCTGCATGATATTGAAAACAATATCACCAAATAAATAACGC
CTTAGTAAGTAGCTTTT""",4))

def test_frequent_words_4():
	assert("AACAA" in frequent_words("""ATACAATTACAGTCTGGAACCGGATGAACTGGCCGCAGGTTAACAACAGAGTTGCCAGGCACTG
CCGCTGACCAGCAACAACAACAATGACTTTGACGCGAAGGGGATGGCATGAGCGAACTGATCGT
CAGCCGTCAGCAACGAGTATTGTTGCTGACCCTTAACAATCCCGCCGCACGTAATGCGCTAACT
AATGCCCTGCTG""",5))

# def test_frequent_words_5():
# 	assert(("AAAAT" and "GGGGT" and "TTTTA") in frequent_words("""CCAGCGGGGGTTGATGCTCTGGGGGTCACAAGATTGCATTTTTATGGGGTTGCAAAAATGTTTT
# TTACGGCAGATTCATTTAAAATGCCCACTGGCTGGAGACATAGCCCGGATGCGCGTCTTTTACA
# ACGTATTGCGGGGTAAAATCGTAGATGTTTTAAAATAGGCGTAAC""",5))